#ifndef EXIT_ERRORS_H
#define EXIT_ERRORS_H

enum EXIT_ERRORS
{
    ERROR_OPEN_SOCKET = 1,
    ERROR_BINDING_SOCKET,
    ERROR_ACCEPTING_CONNECTION,
    ERROR_LISTEN,
    ERROR_ACCEPT,
};

#endif // EXIT_ERRORS_H